###################################################################
server:
  #端口号
#  port: 8081
  port: 9615
#  ssl:
#    key-store: classpath:huecmx.xyz.jks
#    key-store-password: 3dz4is0266w
#    key-store-type: JKS
############################################################################
#链接数据库配置
spring:
  datasource:
    #数据库名称
    name: health
    url: jdbc:mysql://101.42.111.16:3306/my_blog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    #数据库账号
    username: root
    #数据库密码
    password: v3h9zwih
    driver-class-name: com.mysql.cj.jdbc.Driver
###########################################################################################
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cmx.pojo
###########################################################################################
#日志
logging:
  level:
    # 设置日志级别：将Mapper接口所在包下的内容设置为debug级别，可以查看执行SQL语句打印
    com.cmx: debug

